Increment3
smamykin/smetrics pull request #3
Opened 2022-12-22 16:05 UTC by smamykin

2022-12-24 13:45 UTC, DimaTheHero commented on internal/agent/api_client.go
> +		loggerInfo:              log.New(os.Stdout, "INFO:    ", log.Ldate|log.Ltime),
Круто, что ты сделал разделение логов по уровням

2022-12-24 13:46 UTC, DimaTheHero commented on internal/agent/api_client.go
> +	post, err := http.Post(url, "text/plain", strings.NewReader(""))
Вместо `strings.NewReader("")` лучше просто передать `nil`:
```go
post, err := http.Post(url, "text/plain", nil)
```

2022-12-24 13:47 UTC, DimaTheHero commented on internal/agent/api_client.go
> +		c.loggerWarning.Printf("error while sending the metrics to server. Error: %s\n", err.Error())
Если мы получили от хттп-клиента ошибку (например, не удалось установить соединение с сервером), то дальше нам выполнение этой функции продолжать нет смысла => делаем `return err` после лога

2022-12-24 13:47 UTC, DimaTheHero commented on internal/agent/api_client.go
> +		c.loggerWarning.Printf("error while sending the metrics to server. Status: %d\n", post.StatusCode)
Тоже самое здесь

2022-12-24 13:48 UTC, DimaTheHero commented on internal/agent/api_client.go
> +	if post.StatusCode != 200 {
Для проверки статус кода (да и для любой другой константной штуки) лучше использовать константы из библиотеки `net/http`:
```go
if post.StatusCode != http.StatusOK
```

2022-12-24 13:49 UTC, DimaTheHero commented on internal/agent/api_client.go
> +	defer post.Body.Close()
Это лучше переместить на строку после проверки `err != nil` - обычно дефер с закрытием пишут сразу после проверки ошибки (не важно, хттп-запрос это или открытие файла), чтобы точно не потерять его потом

2022-12-24 13:50 UTC, DimaTheHero commented on internal/agent/api_client.go
> +	}
Нам необязательно это делать для пустого тела ответа, просто закрываем body и делаем return

2022-12-24 13:51 UTC, DimaTheHero commented on internal/agent/api_client.go
> +		panic(fmt.Errorf("cannot read the response body. url: %s", url))
И да, мы никогда не используем панику для обработки ошибок в логике сервиса. Паника - это исключительная ситуация, которую нет возможности обработать никак иначе, кроме как бросив сигнал "шеф, все пропало!" вверх по стеку вызовов. В нашем случае, мы можем просто сделать return + залоггировать
P.S. но лучше весь этот блок кода убрать, он не нужен

2022-12-24 13:52 UTC, DimaTheHero commented on internal/agent/api_client.go
> +func getMetricAggregatorPath(metricType string, metricName string, metricValue string) (path string) {
Чтобы сократить сигнатуру функции, для аргументов одинакового типа достаточно указать тип только один раз:
```go 
func getMetricAggregatorPath(metricType, metricName, metricValue string) (path string) {
```

Плюс, сюда же можно добавить `baseURL` чтобы добавлять здесь его префиксом, чтобы не конкатенировать результат этой функции в месте ее вызова

2022-12-24 13:58 UTC, DimaTheHero commented on internal/agent/metric_provider.go
> +	value int
давай назовем это поле delta, чтобы не путаться

2022-12-24 13:59 UTC, DimaTheHero commented on internal/agent/metric_provider.go
> +}
И сгруппируем методы так, чтобы они не в перемешку были, а под каждым объявлением реализации - свой набор реализаций методов 
Тяжело читать

2022-12-24 13:59 UTC, DimaTheHero commented on internal/server/handlers/get_handler.go
> +	case "gauge":
Давай здесь использовать константы

2022-12-24 14:01 UTC, DimaTheHero commented on internal/server/handlers/list_handler.go
> +	t, err := template.New("list").Parse("<html><ol>{{ range .GaugeMetrics }}<li>{{.Name}}:{{.Value}}</li>{{end}}</ol><ol>{{ range .CounterMetrics }}<li>{{.Name}}:{{.Value}}</li>{{end}}</ol></html>")
Круто, что ты сделал простую вебморду для этого, но давай вынесем строку с хтмлиной в отдельную константу и добавим отступы:
```go
const listMetricsTmpl  = `
<html>
    <ol>{{ range .GaugeMetrics }}
        <li>{{.Name}}:{{.Value}}</li>{{end}}
    </ol>
    <ol>{{ range .CounterMetrics }}
        <li>{{.Name}}:{{.Value}}</li>{{end}}
    </ol>
</html>`

2022-12-24 14:03 UTC, DimaTheHero commented on internal/server/handlers/update_handler.go
> +	GetAllCounters() []storage.CounterMetric
Давай здесь на всякий случай добавим тоже `error` вторым значением. В будущем, когда хранилка у нас будет не в памяти, на в любом другом месте подразумевающим ввод-вывод, нам нужно будет иметь возможность пробросить ошибку.

2022-12-24 14:04 UTC, DimaTheHero commented on internal/server/handlers/update_handler.go
> +	if r.Method != "POST" || len(pathElements) != 5 {
Тут тоже давай константу `http.MethodPost` использовать для проверки

2022-12-24 14:07 UTC, DimaTheHero commented on internal/server/storage/mem_storage.go
> +	metricInstance.Value = metricInstance.Value + value
Мне не очень нравится, что эта бизнес-логика находится на уровне хранилки. Мы можем оставить механику апсерта, но давай мы не будем делать никакой арифметики здесь а просто перезаписывать передаваемое значение в мапке по ключу. Соответственно, логика с прибавлением или заменой значения (в зависимости от типа метрики) уедет в хэндлеры (а лучше, конечно же, в отдельный слой с бизнос-логикой).

2022-12-24 14:10 UTC, DimaTheHero commented on internal/server/handlers/update_handler.go
> +	metricValue := pathElements[4]
Давай, тогда, здесь тоже заменим этот код на средства библиотеки go-chi

2022-12-24 14:10 UTC, DimaTheHero commented on internal/server/handlers/update_handler.go
> +	if r.Method != "POST" || len(pathElements) != 5 {
Ну и этот код нам тоже не нужен, тк матчинг методов делает роутер go-chi

2022-12-24 14:11 UTC, DimaTheHero requested changes
Все отлично, но есть замечания (по большей части стилистические)

2022-12-25 13:25 UTC, smamykin commented on internal/agent/api_client.go
> +		c.loggerWarning.Printf("error while sending the metrics to server. Error: %s\n", err.Error())
:ballot_box_with_check:

2022-12-25 13:29 UTC, smamykin commented on internal/agent/api_client.go
> +	defer post.Body.Close()
:ballot_box_with_check:

2022-12-25 13:34 UTC, smamykin commented on internal/agent/api_client.go
> +	post, err := http.Post(url, "text/plain", strings.NewReader(""))
:ballot_box_with_check: Правлено

2022-12-25 13:34 UTC, smamykin commented on internal/agent/api_client.go
> +		c.loggerWarning.Printf("error while sending the metrics to server. Status: %d\n", post.StatusCode)
:ballot_box_with_check: Правлено

2022-12-25 13:35 UTC, smamykin commented on internal/agent/api_client.go
> +	if post.StatusCode != 200 {
:ballot_box_with_check:

2022-12-25 13:35 UTC, smamykin commented on internal/agent/api_client.go
> +	}
:ballot_box_with_check: удалил

2022-12-25 13:37 UTC, smamykin commented on internal/agent/api_client.go
> +func getMetricAggregatorPath(metricType string, metricName string, metricValue string) (path string) {
:ballot_box_with_check: Метод также переименовал в getUpdateMetricURL

2022-12-25 13:39 UTC, smamykin commented on internal/agent/metric_provider.go
> +	value int
:ballot_box_with_check:

2022-12-25 13:39 UTC, smamykin commented on internal/agent/metric_provider.go
> +	value int
:ballot_box_with_check:

2022-12-25 13:39 UTC, smamykin commented on internal/agent/metric_provider.go
> +}
:ballot_box_with_check:

2022-12-25 13:39 UTC, smamykin commented on internal/agent/metric_provider.go
> +}
:ballot_box_with_check:

2022-12-25 13:40 UTC, smamykin commented on internal/server/handlers/get_handler.go
> +	case "gauge":
:ballot_box_with_check:

2022-12-25 13:40 UTC, smamykin commented on internal/server/handlers/list_handler.go
> +	t, err := template.New("list").Parse("<html><ol>{{ range .GaugeMetrics }}<li>{{.Name}}:{{.Value}}</li>{{end}}</ol><ol>{{ range .CounterMetrics }}<li>{{.Name}}:{{.Value}}</li>{{end}}</ol></html>")
:ballot_box_with_check:

2022-12-25 13:41 UTC, smamykin commented on internal/server/handlers/update_handler.go
> +	GetAllCounters() []storage.CounterMetric
:ballot_box_with_check:

2022-12-25 13:43 UTC, smamykin commented on internal/server/handlers/update_handler.go
> +	if r.Method != "POST" || len(pathElements) != 5 {
:ballot_box_with_check: переделал получение значений slug на использование go-chi

2022-12-25 13:45 UTC, smamykin commented on internal/server/storage/mem_storage.go
> +	metricInstance.Value = metricInstance.Value + value
:ballot_box_with_check: Оставил здесь только установку в map значения по ключу и info-лог.

2022-12-25 13:45 UTC, smamykin commented on internal/server/handlers/update_handler.go
> +	metricValue := pathElements[4]
:ballot_box_with_check:

2023-01-14 10:22 UTC, merged