Increment8
smamykin/smetrics pull request #8
Opened 2023-01-21 13:10 UTC by smamykin

2023-01-24 06:04 UTC, Barugoo commented on cmd/agent/main.go
> +		Client:   agent.NewClient("http://" + cfg.Address),
Часть с `"http://"` бы тоже утащить в `cfg.Address` - например, локально у тебя обычно http, а в боевых условиях https и хотелось бы это конфигурировать не лазя в код

2023-01-24 06:05 UTC, Barugoo commented on internal/agent/api_client.go
> +			return body, err
Давай здесь обернем ошибку, чтобы было понятнее, какая функция из двух ее вернула:
```go
return body, fmt.Errorf("unable to parse gauge value: %w", err)

2023-01-24 06:06 UTC, Barugoo commented on internal/agent/api_client.go
> +	return body, err
можно написать в одну строку:
```
return json.Marshal(metrics)

2023-01-24 06:15 UTC, Barugoo commented on internal/server/handlers/handler.go
> +		return
Лучше не вызыать `return` без перечисления возвращаемых значений- это считается дурным тоном в Go, особенно когда функции длиннее пары строк. Понятно, что возвращаем мы `metric` и `err`, но читающему код программисту приходится напрягаться чуть больше чтобы понять какое значение имели эти переменные при вызове отдельно взятого `return`. 

Также, рекомендую явно возвращать `nil` в качестве ошибки, чтобы подсвечивать благоприятные кейсы

2023-01-24 06:24 UTC, Barugoo commented on internal/server/server/gzip_middleware.go
> +			r.Body = io.NopCloser(reader)
Не очень удобно, что для сжатых запросов мы с текущей реализацией дважды считываем тело - в gzipMiddleware и непосредственно в хэндлерах. Одна из прекрасных сторон пакета `io` это возможность наслаивать друг на друга `Reader`'ы (и `Writer`'ы) сколько угодно и затем вызвать один раз метод `Read` (`Write`) и все эти прослойки поочередно будут применяться к лежащему под капотом потоку байт.

Поэтому правильнее здесь было бы написать так:
```go
if r.Header.Get("Content-Encoding") == "gzip" {
	gz, err := gzip.NewReader(r.Body)
 	if err != nil {
 		http.Error(w, err.Error(), http.StatusInternalServerError)
 		return
 	}
 	// не забывайте потом закрыть *gzip.Reader
 	defer gz.Close()

        r.Body = gz
}

2023-01-24 06:29 UTC, Barugoo commented on internal/server/server/server.go
> +	r.Method("POST", "/value/", handlers.NewGetHandler(repository, ParameterBag{}))
Я вижу что ты проделал очень много качественной работы чтобы сделать как можно больше общего кода для JSON и URL-param хэндлеров. Но иногда гораздо проще просто сделать несколько наборов хэндлеров под разные форматы входных данных:
```go
r.Method("POST", "/update/{metricType}/{metricName}/{metricValue}", handlers.NewUpdateHandler(
 repository,
 ParameterBag{},
))
r.Method("GET", "/value/{metricType}/{metricName}", handlers.NewGetHandler(
 repository,
 ParameterBag{},
))

// for json handlers
r.Method("POST", "/update/", handlers.NewUpdateHandlerJSON(repository, ParameterBag{}))
r.Method("POST", "/value/", handlers.NewGetHandlerJSON(repository, ParameterBag{}))

2023-01-24 06:35 UTC, Barugoo commented on internal/server/server/server.go
> +	}
Мне кажется, что все эти штуки лучше утащить из сервера - кажется в сервер лучше просто передавать интерфейс хранилки. Иначе у нас получается слишком большая связность - сделаем gRPC сервер рядом с хттпшным и придется это все повторять там. 

Давай лучше все что относится к подробностями работы хранилки в файле утащим в storage и будем стартовать где-то поближе к `main`

2023-01-24 06:39 UTC, Barugoo commented on internal/server/server/server.go
> +	memStorage.AddObserver(getLoggerObserver(loggerInfo))
Это все тоже лучше утащить в main

2023-01-24 06:40 UTC, Barugoo commented on internal/server/server/server.go
> +}
Тоже будто бы здесь хранить не очень удобно. Давай сделаем эту функцию экспортируемой, утащим в пакет storage и в main будем ее вызывать при старте приложения и инициализации хранилки

2023-01-24 06:42 UTC, Barugoo commented on internal/server/storage/fs_persister.go
> +	err = os.WriteFile(f.fileName, data, 0664)
Не очень удобно, что мы открываем файл каждый раз заново. Давай просто при запуске приложения его один раз откроем, и будем хранить в структуре `FsPersister` полем `os.File` и просто перезаписывать его при вызове `Flush`

2023-01-24 06:43 UTC, Barugoo commented on internal/server/storage/fs_persister.go
> +	data, err := json.MarshalIndent(dump, "", "  ")
Кстати очень правильный подход - в файле храним джейсонину а в коде работаем с мапкой, для которой операции поиска/вставки/удаления уже определны самим Го

2023-01-24 06:43 UTC, Barugoo requested changes
Хорошо, есть замечания, посмотри пожалуйста
А так - супер!

2023-01-25 17:08 UTC, smamykin commented on cmd/agent/main.go
> +		Client:   agent.NewClient("http://" + cfg.Address),
Сделал возможность добавить схему опциональной, т.е. можно указывать и `localhost:8080` и `https://localhost:8008`. Если не указывать - подстваится `http://`.

Иначи автотесты падают.

2023-01-25 17:08 UTC, smamykin commented on internal/agent/api_client.go
> +			return body, err
Правлено.

2023-01-25 17:08 UTC, smamykin commented on internal/agent/api_client.go
> +	return body, err
Правлено

2023-01-25 17:09 UTC, smamykin commented on internal/server/handlers/handler.go
> +		return
Понял. Правлено.

2023-01-25 17:09 UTC, smamykin commented on internal/server/server/gzip_middleware.go
> +			r.Body = io.NopCloser(reader)
Правлено

2023-01-25 17:11 UTC, smamykin commented on internal/server/server/server.go
> +	}
:white_check_mark:  Убрал это все из пакета server.

2023-01-25 17:11 UTC, smamykin commented on internal/server/server/server.go
> +	memStorage.AddObserver(getLoggerObserver(loggerInfo))
:white_check_mark:

2023-01-25 17:12 UTC, smamykin commented on internal/server/server/server.go
> +}
:white_check_mark:

2023-01-25 17:12 UTC, smamykin commented on internal/server/storage/fs_persister.go
> +	err = os.WriteFile(f.fileName, data, 0664)
:white_check_mark:

2023-01-26 23:29 UTC, Barugoo approved these changes
Отлично, работу принимаю!

2023-01-31 13:09 UTC, merged